config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete 'logout', to: 'sessions#destroy'
  
  get "signup",to: "users#new"
  resources :users, only: [:index, :show, :new, :create]
  
  
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: {maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :name , presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255},
                      format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                      uniqueness: {case_sensitive: false}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
     redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email,password)
      flash[:success] = "ログインに成功しました"
      redirect_to @user
    else
      flash.now[:danger] = "rログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
private

def login(email,password)
  @user = User.find_by(email: email)
  if @user &&  @user.authenticate(password)
    #ログイン成功
    session[:user_id] = @user.id
    return true
  else
    #ログイン失敗
    return false
  end
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all.order(id: :desc).page(params[:page]).per(10)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
     
    if @task.save
      flash[:success] = "タスクが追加されました"
      redirect_to @task
    else
      flash[:danger] = "タスクの追加ができませんでした"
      render :new
    end
  end
  

  def edit
  end

  def update
    
    if @task.update(task_params)
      flash[:succes] = "タスクを変更しました"
      redirect_to @task
    else 
      flash[:danger] = "タスクの変更ができませんでした"
      render :edit
    end
  end

  def destroy
    @task.destroy
    
    flash[:success]="タスクが削除されました"
    redirect_to tasks_url
  end
  
  private
  
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:content, :status)
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index,:show]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save 
      flash[:success] = "ユーザーを登録しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザーが登録できませんでした"
      render :new
    end
  end
  
private
  
def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_task.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm nabvar-dark bg-dark">
        <a class="navbar-brand" href="/">Tasklist</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <% if logged_in? %>
                    <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item"><%= link_to "My profile",user_path(current_user) %></li>
                            <li class="dropdown-driver"></li>
                            <li class="dropdown-item"><%= link_to "Logout", logout_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Login" , login_path, class: "nav-link" %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shirink-to-fit=no" >
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet"  href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
    </header>
    <div class="container">
      <%= render 'layouts/flash_task' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-6">

<%= form_with(model: task, local: true) do |f| %>
    <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-warning"
      <ul class="mb-0">
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :status,"ステータス" %>
    <%= f.text_field :status,class: "form-control" %>    
  </div>  
  <div class="form-group">
    <%= f.label :content ,"タスク" %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  
    <%= f.submit "追加", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/tasks/edit.html.erb
<h2>id: <%= @task.id %> のメッセージ編集ページ</h2>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<% if @tasks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>タスク</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id,task_path(task) %></td>
        <td><%= task.status %></td>
        <td><%= task.content %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div>
  <%= paginate @tasks %>
  </div>
<% end %>

<%= link_to "新規追加",new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h2>タスクの追加</h2>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h2>id:<%= @task.id %>の詳細ページ</h2>


<table class="table">
    
    <tbody>
        <tr>
            <td>ステータス</td>
            <th><p><%= @task.status %></p></th>
        </tr>
        <tr>
            <td>タスク</td>
            <th><p><%= @task.content %></p></th>
        </tr>
    </tbody>
</table>


<%= link_to "一覧へ戻る",tasks_path, class: "btn btn-primary" %>
<%= link_to "編集する" ,edit_task_path(@task), class: "btn btn-primary" %>
<%= link_to 'このタスクを削除する', @task,class: "btn btn-danger", method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザー:<%= current_user.name %></p>
<% else %>
<div class="jumbotron">
  <div class="text-center">
      <h1>Welocome to TaskList</h1></h1>
      <%= link_to "Sign Up", signup_path , class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each  do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, {size:50}) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to "View Profile", user_path(user) %></p>
          </div>
        </div>
      </li>  
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render "users" , users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "Email"%>
        <%= f.text_field :email, class: "form-control" %>
      </div> 
      
      <div class="form-group">
        <%= f.label :password, "Pass" %>
        <%= f.text_field :password , class: "form-control" %>
      </div>
      
      <div class="form-grouup">
        <%= f.label :password_comfirmation, "Confirmation" %>
        <%= f.text_field :password_comfirmation, class: "form-control mb-3" %>
      </div>
      
      <%= f.submit "Sign Up", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, {size:500})  %>" alt="">
      </div>
    </div>
  </aside>  
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">Photos</a></li>
      <li class="nav-ietm"><a href="#" class="nav-link">Followings</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followers</a></li>
    </ul>
  </div>
</div>